// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_trading_app/core/storage/chart_cache/chart_cache_hive.dart';
import 'package:flutter_trading_app/core/storage/hive_adapters/candle_adapter.dart';
import 'package:flutter_trading_app/core/storage/replay/replay_hive.dart';
import 'package:flutter_trading_app/core/storage/replay_storage.dart';
import 'package:flutter_trading_app/features/market/data/models/candle_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CandleModelAdapter());
    registerAdapter(ChartCacheEntityAdapter());
    registerAdapter(HiveCandleAdapter());
    registerAdapter(ReplayStateEntityAdapter());
    registerAdapter(ReplayStateEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CandleModelAdapter());
    registerAdapter(ChartCacheEntityAdapter());
    registerAdapter(HiveCandleAdapter());
    registerAdapter(ReplayStateEntityAdapter());
    registerAdapter(ReplayStateEntityAdapter());
  }
}
